apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: 
    app: backend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ericcgu/backend
        imagePullPolicy: Always
        ports:
        - name: backendport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: 
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 8081
      targetPort: backendport
  type: LoadBalancer