apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: 
    app: backend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: JAEGER_AGENT_HOST
          value: simplest-agent.observability.svc.cluster.local
        image: catzzzlol/backend:latest
        imagePullPolicy: Always
        name: backend
        ports:
        - name: backendport
          containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  name: backend
  labels: 
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 8081
      targetPort: backendport
  type: LoadBalancer