apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: 
    app: frontend
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: frontend
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ihnatenkolv/frontend-test
        imagePullPolicy: Always
        ports:
        - name: frontendport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels: 
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 8080
      targetPort: frontendport
  type: LoadBalancer
